#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          ML,            tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          MR,            tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

task main()
{
	int cor1 = getColorName(S1);
	int cor2 = getColorName(S2);
		int cor3 = getColorName(S3);
		//andar para frente
	while(cor3 == 1){

	setMultipleMotors(-50,motorA, motorD);
	wait(250,milliseconds);
		stopMotor(motorA);
		stopMotor(motorD);

}
	// virar direita
		displayBigTextLine(24,"cor1","estou aqui");
		if (cor2 == 1 && cor1 == 6) {
			setMotor(motorD,-100 );
			setMotor(motorA, 100);
			wait(500,milliseconds);
		}

		//virar esquerda
		if (cor1 == 1 && cor2 == 6) {
			setMotor(motorD,-100);
			setMotor(motorA, 100);
			wait(500,milliseconds);
		}

		if (cor2 == 3) {
			setMotor(motorD,-150 );
			setMotor(motorA, 150);
			wait(900,milliseconds);
		}

		if (cor1 == 3) {
			setMotor(motorA,-150);
			setMotor(motorD, 150);
			wait(900,milliseconds);
		}
}// task
