#pragma config(Sensor, S1,     c1,             sensorEV3_Color)
#pragma config(Sensor, S2,     c2,             sensorEV3_Color)
#pragma config(Sensor, S3,     c3,             sensorEV3_Color)
#pragma config(Motor,  motorA,          m1,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          m2,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	int cor1 = getColorName(S1);
	int cor2 = getColorName(S2);
	while (true) {
		setMultipleMotors(200,m1,m2);
		wait(250,milliseconds);
		stopAllMotors();
		if (cor2 == 1 && cor1 == 6) {
				setMotor(m1,-100 );
				setMotor(m2, 100);
				wait(500,milliseconds);
		}
		if (cor1 == 1 && cor2 == 6) {
				setMotor(m2,-100);
				setMotor(m1, 100);
				wait(500,milliseconds);
		}
		if (cor2 == 3) {
				setMotor(m1,-150 );
				setMotor(m2, 150);
				wait(900,milliseconds);
		}

		if (cor1 == 3) {
				setMotor(m1,-150);
				setMotor(m2, 150);
				wait(900,milliseconds);
		}
  }//while
}// task
